### ISSUE TITLE
Unexpected `ArgumentError: invalid byte sequence in UTF-8`

### ISSUE THREAD

**Issue by opsidao** [metainspector/metainspector#247]
I know that this is a know issue and that it has been handled in the past, but it was my understanding after looking at the previous issues (#190, #187, #220) that I should expect a `MetaInspector::RequestError` when there's a problem decoding a site, but I have one url that is actually throwing an ArgumentError, which is kind of unexpected and a bit broad to handle.

Here's a sample session showing the issue:

```shell
root@b9d862866991:/app# cat Gemfile | grep metainspector
gem 'metainspector', '= 5.6.0'
root@b9d862866991:/app# bundle exec rails c
Loading development environment (Rails 5.1.6.2)
[1] pry(main)> MetaInspector.new('http://pharmaagentur.ch/')
(pry) output error: #<ArgumentError: invalid byte sequence in UTF-8>
/bundle/gems/metainspector-5.6.0/lib/meta_inspector/parsers/texts.rb:60:in `gsub'
/bundle/gems/metainspector-5.6.0/lib/meta_inspector/parsers/texts.rb:60:in `block in find_best_title'
/bundle/gems/metainspector-5.6.0/lib/meta_inspector/parsers/texts.rb:60:in `map!'
/bundle/gems/metainspector-5.6.0/lib/meta_inspector/parsers/texts.rb:60:in `find_best_title'
/bundle/gems/metainspector-5.6.0/lib/meta_inspector/parsers/texts.rb:13:in `best_title'
/bundle/gems/metainspector-5.6.0/lib/meta_inspector/document.rb:64:in `to_hash'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:118:in `convert_to_hash'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:47:in `awesome_self'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:28:in `format'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:115:in `unnested'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:74:in `awesome'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
/bundle/gems/awesome_print-1.8.0/lib/awesome_print/custom_defaults.rb:45:in `block in pry!'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:399:in `show_result'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:368:in `block in handle_line'
/bundle/gems/pry-0.12.2/lib/pry/pry_class.rb:401:in `critical_section'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:367:in `handle_line'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
/bundle/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
/bundle/gems/pry-0.12.2/lib/pry/repl.rb:77:in `block in repl'
/bundle/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/bundle/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/bundle/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/bundle/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/bundle/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/bundle/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/bundle/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/bundle/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/bundle/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/bundle/gems/railties-5.1.6.2/lib/rails/commands/console/console_command.rb:62:in `start'
/bundle/gems/railties-5.1.6.2/lib/rails/commands/console/console_command.rb:17:in `start'
/bundle/gems/railties-5.1.6.2/lib/rails/commands/console/console_command.rb:97:in `perform'
/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/bundle/gems/railties-5.1.6.2/lib/rails/command/base.rb:63:in `perform'
/bundle/gems/railties-5.1.6.2/lib/rails/command.rb:44:in `invoke'
/bundle/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

Not sure what the issue is as I haven't really digged into it, but I assume the site is partially correct but some part of the metadata is incorrect?

In any case, I suppose that this should be `rescued` somewhere and converted into a `RequestError`.

**Comment by jaimeiniesta** [comment]
Thanks for the report! You're right, this should be converted into a proper error. I'm quite busy these days but I'll be happy to review a PR.

**Comment by opsidao** [comment]
Sure, I'll try to give it some minutes this week at some point, if time allows 😉

**Comment by ganbootyard** [comment]
Hi all, encountered this today. In my case, the `ArgumentError: invalid byte sequence in UTF-8` only shows after I call the `.best_title` method.

This is how I call it `page = MetaInspector.new('http://yogaclass.com/links.html')`, this does not return any error but only when I do `page.best_title`.

Using the force encoding option, from #239, returns the correct error directly though.

**Comment by jaimeiniesta** [comment]
Just checked with MetaInspector 5.11.1, this is no longer an issue (please reopen if it happens again).

In the case submitted by @ghost it works without forcing the encoding as well:

```ruby
irb(main):010:0> page = MetaInspector.new('http://yogaclass.com/links.html')
irb(main):011:0> page.best_title
=> "YogaClass\u0099 Links"

irb(main):012:0> page = MetaInspector.new('http://yogaclass.com/links.html', encoding: 'UTF-8')
irb(main):013:0> page.best_title
=> "YogaClass� Links"
```
